# -*- coding: utf-8 -*-
"""Ejercicio2_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Buol_eKLhBa7HkHycV9T23qD2W1fttqY

# Algoritmo de Thomas modificado
"""

def Thomas_adelante(DP, DS, DI, b):
    n = len(DP)
    x = [0] * n  # Lista donde se van a guardar las soluciones

    # Eliminacion hacia delante
    for i in range(1, n):
        factor = DI[i-1] / DP[i-1]
        DP[i] -= factor * DS[i-1]
        b[i] -= factor * b[i-1]

    # Sustitución de delante
    x[0] = b[0] / DP[0]
    for i in range(1, n):
        x[i] = (b[i] - DI[i-1] * x[i-1]) / DP[i]

    return x

# Definimos n
n = int(input("Ingrese el tamaño de la matriz: "))  # Se puede cambiar a cualquier valor

# Generar la matriz
DP = [2] * n  # Diagonal principal
DS = [-1] * (n-1)  # Diagonal superior
DI = [-1] * (n-1)  # Diagonal inferior
b = [1] * n  # Vector b

# Resolvemos el sistema usando el algoritmo de Thomas con sustituión hacia delante
solucion = Thomas_adelante(DP[:], DS[:], DI[:], b[:])  # Pasamos copias para evitar modificar las originales
print("Solución:", solucion)